export const RENDER_DATA = [
  {
    title: 'Get url from API + SVG filter',
    kind: 'api-get-url',
    contentId: 'bender',
    svgFilterId: 'svg-filter'
  },
  {
    title: 'Generated by API on the fly',
    kind: 'api-generated',
    contentId: ''
  }
];
